package com.smartapps.jmdb.enumeration.model

data class User(
    val agency_id: String = "",
    val allowdesktoplogin: String = "",
    val allowmobilelogin: String = "",
    val created_at: String = "",
    val created_by: String = "",
    val email: String = "",
    val first_use: String = "",
    val group_id: String = "",
    var id: Int = 0,
    val inactive: String = "",
    val name: String = "",
    val organization_code:  String = "",
    val organization_id:  String = "",
    val password: String  = "",
    val prev_username: String = "",
    val remember_token: String = "",
    val reset_expiry_date: String = "",
    val reset_token: String = "",
    val service_code: String = "",
    val service_id: String = "",
    val tax_office_id:  String = "",
    val updated_at: String = "",
    val updated_by: String = "",
    val user_code: String = "",
    val user_phone: String = "",
    val username: String = "",
    var uid: String = ""
)